{
    'name': 'RiadaHR Subscriotion Control',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Limit the number of employees with users in the system',
    'description': 'This module limits the number of employees that can be created in the system.',
    'author': 'RiadaHR',
    'website': 'alriada.tech',
    'depends': ['hr'],
    'data': [],
    "license": "AGPL-3",
    'installable': True,
    'application': False,
    'auto_install': False,
}
